### ISSUE TITLE
Return value from __repr__ should be callable in eval()

### ISSUE THREAD

**Issue by mlew** [myusuf3/delorean#64]
It is common Python practice to make the string value returned from the __repr__ method evaluatable.  For instance, I should be able to do the following:

```python
>>> d1 = Delorean(datetime(2015, 1, 1), timezone='UTC')
>>> d2 = eval(repr(d1))
>>> d1 == d2
True
```

The current implementation raises a SyntaxError.

```python
>>> d1 = Delorean(datetime(2015, 1, 1), timezone='UTC')
>>> d2 = eval(repr(d1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
    Delorean(datetime=2015-01-01 00:00:00+00:00, timezone=UTC)
                                  ^
SyntaxError: invalid syntax
```

**Comment by myusuf3** [comment]
Do you have a suggested return value for the **repr**?

**Comment by mlew** [comment]
Yes, I've got a PR coming shortly.  It should be something like:

```python
Delorean(datetime=datetime(2015, 1, 1, 0, 0), timezone='UTC')
```
